### ISSUE TITLE
Freesurfer 7.1.0

### ISSUE THREAD

**Issue by soichih** [pegasus-isi/freesurfer-osg-workflow#10]
I'd like to request for freesurfer 7.1.0 container to be made available

```
ls: cannot access /cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo-freesurfer:7.1.0/: No such file or directory
Error: unable to access /cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo-freesurfer:7.1.0
```

Also, the Freesurfer 7.0.0 should be removed as it was recalled by the developer.
> https://surfer.nmr.mgh.harvard.edu/fswiki/ReleaseNotes

**Comment by rynge** [comment]
I  have added 7.1.1. It is now the default.
