### ISSUE TITLE
workflow-generator.py: error: argument --inputs-def is required

### ISSUE THREAD

**Issue by Davi1990** [pegasus-isi/freesurfer-osg-workflow#12]
Hi, 

I am trying to run the test script from the /freesurfer-osg-workflow directory using the following command:

`./submit.sh --input-def example-run.yml `

however I got the following error message: 

> workflow-generator.py: error: argument --inputs-def is required

Do you have an idea on what is going on? 

Thanks

**Comment by rynge** [comment]
Handling this issue in the OSG ticket system
