### ISSUE TITLE
Stream freesurfer log back to the submit host

### ISSUE THREAD

**Issue by soichih** [pegasus-isi/freesurfer-osg-workflow#4]
Would it be possible to stream the output from the recon-all command back to the submit host while the job is being executed? I can live without this, but I think users will want to see how the job is progressing. 

I am particularly interested in the following markers in the stdout
```

#--------------------------------------------
#@# ASeg Stats Mon Apr 20 21:52:51 UTC 2020

...

#-----------------------------------------
#@# WMParc Mon Apr 20 21:53:29 UTC 2020

...

#--------------------------------------------
#@# BA_exvivo Labels lh Mon Apr 20 21:59:04 UTC 2020

...

#--------------------------------------------
#@# BA_exvivo Labels rh Mon Apr 20 22:01:08 UTC 2020
```

These markers tell where it is in terms of overall processing.

If something similar to this can be output to the log, I can then relay that to the users. Would this be difficult to do?

**Comment by rynge** [comment]
This one is difficult as OSG has turned off stream for scalability reasons. I will bring it up with the Pegasus team to see if there is anything we can on in that setting.

**Comment by rynge** [comment]
Sorry, there is no way to stream outputs at this point. This is because the outputs are captured as part of other provenance data, and they are kept together.

**Comment by soichih** [comment]
I see. Is it possible to show the status of the workflow from pegasus? Pegasus knows which part of the freesurfer is currently executed, correct?

**Comment by rynge** [comment]
pegasus-status -l [wfdir] should give you the current status, with the job and % done.
