### ISSUE TITLE
Add capability to specify freesurfer version

### ISSUE THREAD

**Issue by soichih** [pegasus-isi/freesurfer-osg-workflow#5]
I believe the current version of freesurfer-osg-workflow runs freesurfer 6.0.1(?). Is there anyway to specify the version of freesurfer? We run 6.0.0 and 6.0.1, and sometimes the dev (nightly build) version. Also, freesurfer 7.0 RC is out now, so I might want to start testing with it also.

**Comment by soichih** [comment]
7.0.0 is out now, btw!

**Comment by rynge** [comment]
Cool - I'm working on supporting these versions. Do you know if there are any major cli changes?

**Comment by soichih** [comment]
There are no major cli changes.
